### PR TITLE
0.4.1 - enable adding handlers for heartbeat messages

### PR DESCRIPTION
**Pull request by cgaustin**

### CODE REVIEW

**Comment by osallou** [comment]
Thanks, please just set release to 0.4.1 and not 0.4.2

**Comment by cgaustin** [comment]
thanks @osallou !  we've been using this project for about a year now, and its been great. much appreciated.   I've added a commit setting the version  to 0.4.1 in setup.py

**Comment by osallou** [comment]
Miss update in changes file ;-)

**Comment by cgaustin** [comment]
sorry about that, done!

**Comment by osallou** [comment]
@cgaustin thanks for your contrib, package has been uploaded to pypi

**Comment by cgaustin** [comment]
excellent, thanks again!

**Pull request merged**
